//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tours (A).
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Request (Space).
        /// </summary>
        public static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All (Backspace).
        /// </summary>
        public static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter (Ins).
        /// </summary>
        public static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests(adult):.
        /// </summary>
        public static string ADULT {
            get {
                return ResourceManager.GetString("ADULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AYS {
            get {
                return ResourceManager.GetString("AYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Statistics (B).
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live View (C).
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel (Esc).
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Selected Tour (C).
        /// </summary>
        public static string CancelSelectedTour {
            get {
                return ResourceManager.GetString("CancelSelectedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change (Enter).
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change year (Y).
        /// </summary>
        public static string ChangeYear {
            get {
                return ResourceManager.GetString("ChangeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Esc).
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseE {
            get {
                return ResourceManager.GetString("CloseE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core options:.
        /// </summary>
        public static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Report (N).
        /// </summary>
        public static string CreateNewReport {
            get {
                return ResourceManager.GetString("CreateNewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests (D).
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration in hours.
        /// </summary>
        public static string DurationInHours {
            get {
                return ResourceManager.GetString("DurationInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Statistics (E).
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End (Enter).
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Images.
        /// </summary>
        public static string EnterImages {
            get {
                return ResourceManager.GetString("EnterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL:.
        /// </summary>
        public static string EnterImageUrl {
            get {
                return ResourceManager.GetString("EnterImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter key point:.
        /// </summary>
        public static string EnterKeyPoint {
            get {
                return ResourceManager.GetString("EnterKeyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Key Points.
        /// </summary>
        public static string EnterKeyPoints {
            get {
                return ResourceManager.GetString("EnterKeyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Starting Time.
        /// </summary>
        public static string EnterStartingTime {
            get {
                return ResourceManager.GetString("EnterStartingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date:.
        /// </summary>
        public static string EnterTourDate {
            get {
                return ResourceManager.GetString("EnterTourDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter year here:.
        /// </summary>
        public static string ESY {
            get {
                return ResourceManager.GetString("ESY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examine grade (E).
        /// </summary>
        public static string Examine {
            get {
                return ResourceManager.GetString("Examine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter (Enter).
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for presence:.
        /// </summary>
        public static string GPC {
            get {
                return ResourceManager.GetString("GPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string GPCask {
            get {
                return ResourceManager.GetString("GPCask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GPCcancel {
            get {
                return ResourceManager.GetString("GPCcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest number.
        /// </summary>
        public static string GuestNumberF {
            get {
                return ResourceManager.GetString("GuestNumberF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Knowledge.
        /// </summary>
        public static string GuideKnowledge {
            get {
                return ResourceManager.GetString("GuideKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Language.
        /// </summary>
        public static string GuideLanguage {
            get {
                return ResourceManager.GetString("GuideLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initital date.
        /// </summary>
        public static string InititalDate {
            get {
                return ResourceManager.GetString("InititalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string IsPresent {
            get {
                return ResourceManager.GetString("IsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined at:.
        /// </summary>
        public static string JoinE {
            get {
                return ResourceManager.GetString("JoinE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key points.
        /// </summary>
        public static string KeyPoints {
            get {
                return ResourceManager.GetString("KeyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Kreiraj {
            get {
                return ResourceManager.GetString("Kreiraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language(N).
        /// </summary>
        public static string LanguageN {
            get {
                return ResourceManager.GetString("LanguageN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF TOURS HELD TODAY.
        /// </summary>
        public static string LiveList {
            get {
                return ResourceManager.GetString("LiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location(Y).
        /// </summary>
        public static string LocationY {
            get {
                return ResourceManager.GetString("LocationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout (Esc).
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Point.
        /// </summary>
        public static string LTVKeyPoint {
            get {
                return ResourceManager.GetString("LTVKeyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode (M).
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark (M).
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string MarkE {
            get {
                return ResourceManager.GetString("MarkE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max guests.
        /// </summary>
        public static string MaxGuests {
            get {
                return ResourceManager.GetString("MaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests : Filtering.
        /// </summary>
        public static string MRF {
            get {
                return ResourceManager.GetString("MRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tours.
        /// </summary>
        public static string MyTours {
            get {
                return ResourceManager.GetString("MyTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tour  (N).
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameG {
            get {
                return ResourceManager.GetString("NameG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No(N).
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of requests:.
        /// </summary>
        public static string NOR {
            get {
                return ResourceManager.GetString("NOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of possible guests.
        /// </summary>
        public static string PossibleGuests {
            get {
                return ResourceManager.GetString("PossibleGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile:.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string RDClose {
            get {
                return ResourceManager.GetString("RDClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string RDDescription {
            get {
                return ResourceManager.GetString("RDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset (Backspace).
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign (R).
        /// </summary>
        public static string Resign {
            get {
                return ResourceManager.GetString("Resign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion (S).
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tour to get statistics|Most visited tour:.
        /// </summary>
        public static string SelectMost {
            get {
                return ResourceManager.GetString("SelectMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests(senior):.
        /// </summary>
        public static string SENIOR {
            get {
                return ResourceManager.GetString("SENIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select grade to examine:.
        /// </summary>
        public static string SGE {
            get {
                return ResourceManager.GetString("SGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show reviews (R).
        /// </summary>
        public static string ShowReviews {
            get {
                return ResourceManager.GetString("ShowReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics (S).
        /// </summary>
        public static string ShowStatistics {
            get {
                return ResourceManager.GetString("ShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartingTime.
        /// </summary>
        public static string StartingTime {
            get {
                return ResourceManager.GetString("StartingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tour (S).
        /// </summary>
        public static string StartTour {
            get {
                return ResourceManager.GetString("StartTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Filtering.
        /// </summary>
        public static string StatisticsFiltering {
            get {
                return ResourceManager.GetString("StatisticsFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base on:.
        /// </summary>
        public static string SuggestionB {
            get {
                return ResourceManager.GetString("SuggestionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SurnameG {
            get {
                return ResourceManager.GetString("SurnameG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests(teen):.
        /// </summary>
        public static string TEEN {
            get {
                return ResourceManager.GetString("TEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Appeal.
        /// </summary>
        public static string TourAppeal {
            get {
                return ResourceManager.GetString("TourAppeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour duration.
        /// </summary>
        public static string TourDuration {
            get {
                return ResourceManager.GetString("TourDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour name.
        /// </summary>
        public static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of guests without voucher:.
        /// </summary>
        public static string VOUCHERMINUS {
            get {
                return ResourceManager.GetString("VOUCHERMINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of guests with voucher:.
        /// </summary>
        public static string VOUCHERPLUS {
            get {
                return ResourceManager.GetString("VOUCHERPLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow options:.
        /// </summary>
        public static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian (X).
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string xxx {
            get {
                return ResourceManager.GetString("xxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English  (Y).
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes(Y).
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Zatvori {
            get {
                return ResourceManager.GetString("Zatvori", resourceCulture);
            }
        }
    }
}
